version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bookapp-db
    environment:
      POSTGRES_DB: bookapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: bookapp-backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      APP_JWT_SECRET: gG7NkEqT8x6z2WkJ1/H8h0e5A6OrKHTl3c8TkB6OvnY=
    restart: unless-stopped

volumes:
  pgdata:
